version: "3"

services:
  react_app:
    container_name: react_app
    build: ./Dockerfile
    command: npm start
    volumes:
      - ./web:/exportLeanCanvas
    ports:
      - 3000:3000

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./web/build:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
